FROM python:3.12.7-slim

# Definir o diretório de trabalho na imagem
WORKDIR /Sprint 04/Desafio/mascarar

# Copiar o restante dos arquivos do projeto
COPY hash.py .

# Comando para iniciar a aplicação
CMD ["python", "hash.py"]
